package com.viciousscan.app.scanner

import com.viciousscan.app.model.*

object ReportGenerator {

    /** Generate an AI-readable markdown README from scan results + project info */
    fun generateAiReadme(report: ScanReport, info: ProjectInfo): String {
        val sb = StringBuilder()
        sb.appendLine("# ${info.appName.ifEmpty { "Android Project" }} — AI Revision Brief")
        sb.appendLine()
        sb.appendLine("## Project Info")
        if (info.developerName.isNotEmpty()) sb.appendLine("- **Developer:** ${info.developerName}")
        if (info.email.isNotEmpty()) sb.appendLine("- **Email:** ${info.email}")
        if (info.githubUsername.isNotEmpty()) sb.appendLine("- **GitHub:** ${info.githubUsername}")
        if (info.repoUrl.isNotEmpty()) sb.appendLine("- **Repo:** ${info.repoUrl}")
        if (info.packageName.isNotEmpty()) sb.appendLine("- **Package:** ${info.packageName}")
        sb.appendLine()
        sb.appendLine("## Scan Summary")
        sb.appendLine("- Files scanned: ${report.scannedFiles.size}")
        sb.appendLine("- Total findings: ${report.findings.size}")
        sb.appendLine("- Project type: ${report.projectType.name}")
        sb.appendLine("- Scan duration: ${report.scanDurationMs}ms")
        sb.appendLine()

        val required = report.findings.filter { it.severity == Severity.REQUIRED }
        val recommended = report.findings.filter { it.severity == Severity.RECOMMENDED }
        val optional = report.findings.filter { it.severity == Severity.OPTIONAL }

        if (required.isNotEmpty()) {
            sb.appendLine("## Required Changes (App will fail without these)")
            required.forEach { f ->
                sb.appendLine()
                sb.appendLine("### ${f.name}")
                sb.appendLine("- **Type:** ${f.type.name.replace('_', ' ')}")
                sb.appendLine("- **Reason:** ${f.reason}")
                if (f.sourceFile != null) {
                    sb.appendLine("- **Found in:** `${f.sourceFile}`${if (f.sourceLine != null) " line ${f.sourceLine}" else ""}")
                }
                if (f.codeSnippet != null) {
                    sb.appendLine("- **Code context:**")
                    sb.appendLine("```")
                    sb.appendLine(f.codeSnippet)
                    sb.appendLine("```")
                }
                if (f.autoFixSnippet != null) {
                    sb.appendLine("- **Fix to apply:**")
                    sb.appendLine("```")
                    sb.appendLine(f.autoFixSnippet)
                    sb.appendLine("```")
                }
            }
            sb.appendLine()
        }

        if (recommended.isNotEmpty()) {
            sb.appendLine("## Recommended Changes")
            recommended.forEach { f ->
                sb.appendLine()
                sb.appendLine("### ${f.name}")
                sb.appendLine("- **Reason:** ${f.reason}")
                if (f.sourceFile != null) sb.appendLine("- **Found in:** `${f.sourceFile}`${if (f.sourceLine != null) " line ${f.sourceLine}" else ""}")
                if (f.autoFixSnippet != null) {
                    sb.appendLine("```")
                    sb.appendLine(f.autoFixSnippet)
                    sb.appendLine("```")
                }
            }
            sb.appendLine()
        }

        if (optional.isNotEmpty()) {
            sb.appendLine("## Optional / Cleanup")
            optional.forEach { f ->
                sb.appendLine("- **${f.name}**: ${f.reason}${if (f.sourceFile != null) " (`${f.sourceFile}`${if (f.sourceLine != null) " L${f.sourceLine}" else ""})" else ""}")
            }
            sb.appendLine()
        }

        sb.appendLine("---")
        sb.appendLine("*Generated by ViciousScan — https://github.com/${info.githubUsername.ifEmpty { "your-username" }}/${info.repoUrl.substringAfterLast("/").ifEmpty { "your-repo" }}*")
        return sb.toString()
    }

    /** Generate a raw code template with all permissions/dependencies blanked out */
    fun generateRawTemplate(report: ScanReport, info: ProjectInfo): String {
        val sb = StringBuilder()
        sb.appendLine("# Raw Code Template — ${info.appName.ifEmpty { "Project" }}")
        sb.appendLine("# Package: ${info.packageName.ifEmpty { "com.your.package" }}")
        sb.appendLine("# Fill in the blanks marked with TODO")
        sb.appendLine()

        val permissions = report.findings.filter { it.type == FindingType.PERMISSION }
        val dependencies = report.findings.filter { it.type == FindingType.GRADLE_DEPENDENCY }

        if (permissions.isNotEmpty()) {
            sb.appendLine("## AndroidManifest.xml — Permissions to add")
            sb.appendLine("```xml")
            sb.appendLine("<manifest xmlns:android=\"http://schemas.android.com/apk/res/android\"")
            sb.appendLine("    package=\"${info.packageName.ifEmpty { "TODO: your.package.name" }}\">")
            sb.appendLine()
            permissions.forEach { f ->
                sb.appendLine("    <!-- ${f.reason} -->")
                if (f.name.contains("ACCESSIBILITY")) {
                    sb.appendLine("    <!-- Accessibility sub-options — choose what applies: -->")
                    sb.appendLine("    <!-- Display: TYPE_VIEW_CLICKED, TYPE_VIEW_FOCUSED, TYPE_WINDOW_STATE_CHANGED -->")
                    sb.appendLine("    <!-- Input: TYPE_VIEW_TEXT_CHANGED, TYPE_VIEW_TEXT_SELECTION_CHANGED -->")
                    sb.appendLine("    <!-- Navigation: TYPE_WINDOWS_CHANGED, TYPE_VIEW_SCROLLED -->")
                    sb.appendLine("    <uses-permission android:name=\"${f.name}\" /> <!-- TODO: verify scope needed -->")
                } else {
                    sb.appendLine("    <uses-permission android:name=\"${f.name}\" /> <!-- TODO: confirm needed -->")
                }
                sb.appendLine()
            }
            sb.appendLine("</manifest>")
            sb.appendLine("```")
            sb.appendLine()
        }

        if (dependencies.isNotEmpty()) {
            sb.appendLine("## build.gradle.kts — Dependencies to add")
            sb.appendLine("```kotlin")
            sb.appendLine("dependencies {")
            dependencies.forEach { f ->
                sb.appendLine("    // ${f.reason}")
                if (f.autoFixSnippet != null) {
                    f.autoFixSnippet.lines().forEach { line ->
                        sb.appendLine("    $line // TODO: verify version")
                    }
                } else {
                    sb.appendLine("    // TODO: add ${f.name}")
                }
                sb.appendLine()
            }
            sb.appendLine("}")
            sb.appendLine("```")
            sb.appendLine()
        }

        sb.appendLine("## Files requiring changes")
        report.findings.filter { it.sourceFile != null }.groupBy { it.sourceFile }.forEach { (file, findings) ->
            sb.appendLine()
            sb.appendLine("### `$file`")
            findings.forEach { f ->
                sb.appendLine("- Line ${f.sourceLine ?: "?"}: **${f.name}** — ${f.reason}")
                if (f.codeSnippet != null) {
                    sb.appendLine("  ```")
                    f.codeSnippet.lines().forEach { sb.appendLine("  $it") }
                    sb.appendLine("  ```")
                    sb.appendLine("  → TODO: ${f.autoFixSnippet ?: "fix manually"}")
                }
            }
        }
        return sb.toString()
    }
}
